In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/pakistan_air_quality_final_clean.csv")
df.head()

,timestamp,city,latitude,longitude,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,...,pressure,date,hour,day_of_week,month,month_name,year,is_weekend,season,aqi_category
0,2025-11-06 00:00:00,Faisalabad,31.4504,73.135,23.7,22.6,598.0,15.9,5.0,58.0,...,1023.4,2025-11-06,0,Thursday,11,November,2025,0,Autumn,Moderate
1,2025-11-06 01:00:00,Faisalabad,31.4504,73.135,25.4,24.2,790.0,21.7,5.6,51.0,...,1023.4,2025-11-06,1,Thursday,11,November,2025,0,Autumn,Moderate
2,2025-11-06 02:00:00,Faisalabad,31.4504,73.135,32.2,30.7,1048.0,29.4,6.5,42.0,...,1023.4,2025-11-06,2,Thursday,11,November,2025,0,Autumn,Moderate
3,2025-11-06 03:00:00,Faisalabad,31.4504,73.135,36.2,34.8,1176.0,33.2,7.2,42.0,...,1023.4,2025-11-06,3,Thursday,11,November,2025,0,Autumn,Moderate
4,2025-11-06 04:00:00,Faisalabad,31.4504,73.135,34.7,33.3,1053.0,29.3,7.6,58.0,...,1023.4,2025-11-06,4,Thursday,11,November,2025,0,Autumn,Moderate

In [3]:
df['city'].value_counts()

city
Faisalabad        2184
Islamabad         2184
Karachi           2184
Lahore            2184
Multan            2184
Peshawar          2184
Quetta            2184
Rahim Yar Khan    2184
Rawalpindi        2184
Sialkot           2184
Name: count, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21840 entries, 0 to 21839
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         21840 non-null  object
 1   city              21840 non-null  object
 2   latitude          21840 non-null  float64
 3   longitude         21840 non-null  float64
 4   pm10              21840 non-null  float64
 5   pm2_5             21840 non-null  float64
 6   carbon_monoxide   21840 non-null  float64
 7   nitrogen_dioxide  21840 non-null  float64
 8   sulphur_dioxide   21840 non-null  float64
 9   ozone             21840 non-null  float64
 10  dust              21840 non-null  float64
 11  temperature       21840 non-null  float64
 12  humidity          21840 non-null  float64
 13  precipitation     21840 non-null  float64
 14  wind_speed        21840 non-null  float64
 15  wind_direction    21840 non-null  float64
 16  pressure          21840 non-null  float64
 17  date              21840 non-null  object
 18  hour              21840 non-null  int64
 19  day_of_week       21840 non-null  object
 20  month             21840 non-null  int64
 21  month_name        21840 non-null  object
 22  year              21840 non-null  int64
 23  is_weekend        21840 non-null  int64
 24  season            21840 non-null  object
 25  aqi_category      21840 non-null  object
dtypes: float64(15), int64(4), object(7)
memory usage: 4.3+ MB

In [5]:
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21840 entries, 0 to 21839
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         21840 non-null  datetime64[ns]
 1   city              21840 non-null  object
 2   latitude          21840 non-null  float64
 3   longitude         21840 non-null  float64
 4   pm10              21840 non-null  float64
 5   pm2_5             21840 non-null  float64
 6   carbon_monoxide   21840 non-null  float64
 7   nitrogen_dioxide  21840 non-null  float64
 8   sulphur_dioxide   21840 non-null  float64
 9   ozone             21840 non-null  float64
 10  dust              21840 non-null  float64
 11  temperature       21840 non-null  float64
 12  humidity          21840 non-null  float64
 13  precipitation     21840 non-null  float64
 14  wind_speed        21840 non-null  float64
 15  wind_direction    21840 non-null  float64
 16  pressure          21840 non-null  float64
 17  date              21840 non-null  object
 18  hour              21840 non-null  int64
 19  day_of_week       21840 non-null  object
 20  month             21840 non-null  int64
 21  month_name        21840 non-null  object
 22  year              21840 non-null  int64
 23  is_weekend        21840 non-null  int64
 24  season            21840 non-null  object
 25  aqi_category      21840 non-null  object
dtypes: datetime64[ns](1), float64(15), int64(4), object(6)
memory usage: 4.3+ MB

In [6]:
df.describe()

,timestamp,latitude,longitude,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,dust,temperature,humidity,precipitation,wind_speed,wind_direction,pressure,hour,month,year,is_weekend
count,21840,21840.000000,21840.000000,21840.000000,21840.000000,21840.0000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000,21840.000000
mean,2025-12-21 11:30:00,31.037740,71.538740,88.416575,82.968141,1580.8587,39.470870,19.466383,63.802106,9.858242,13.721964,64.741667,0.018022,5.339116,178.497070,1020.052885,11.500000,7.538462,2025.384615,0.285714
min,2025-11-06 00:00:00,24.860700,66.975000,0.500000,0.500000,91.0000,0.000000,0.100000,0.000000,0.000000,-5.900000,4.000000,0.000000,0.000000,2.000000,1006.400000,0.000000,1.000000,2025.000000,0.000000
25%,2025-11-28 17:45:00,30.157500,70.295200,40.500000,34.700000,741.0000,13.400000,10.600000,21.000000,1.000000,10.200000,52.000000,0.000000,2.900000,59.000000,1017.600000,5.750000,1.000000,2025.000000,0.000000
50%,2025-12-21 11:30:00,31.500050,72.270900,68.500000,62.400000,1296.5000,30.400000,17.700000,55.000000,3.000000,13.300000,64.000000,0.000000,4.200000,177.000000,1020.000000,11.500000,11.000000,2025.000000,0.000000
75%,2026-01-13 05:15:00,33.565100,73.135000,117.800000,112.500000,2113.2500,57.800000,26.300000,100.000000,8.000000,16.900000,81.000000,0.000000,6.600000,295.000000,1023.400000,17.250000,12.000000,2026.000000,1.000000
max,2026-02-04 23:00:00,34.015100,74.522900,488.000000,486.200000,11482.0000,185.100000,75.100000,265.000000,711.000000,30.400000,100.000000,10.000000,33.400000,360.000000,1030.800000,23.000000,12.000000,2026.000000,1.000000
std,NaN,2.670825,2.583617,66.010440,65.742106,1145.6328,32.286339,11.582885,50.401229,32.531054,5.043094,20.267453,0.209813,3.919920,119.004313,3.492249,6.922345,5.097644,0.486515,0.451764

In [7]:
df['pm2_5'].sort_values(ascending=False).head(20)

1804     486.2
1803     441.4
10315    426.5
10316    419.1
10314    415.4
1443     406.1
1434     400.5
1805     397.7
1435     393.9
1506     393.9
10317    387.4
10313    386.5
1266     385.6
1507     384.6
1444     381.8
844      381.8
1554     381.8
1267     380.0
1746     379.0
1436     377.2
Name: pm2_5, dtype: float64

In [8]:
df[['timestamp', 'city', 'pm2_5']].sort_values('pm2_5', ascending=False).head(20)

                timestamp        city  pm2_5
1804  2026-01-20 04:00:00  Faisalabad  486.2
1803  2026-01-20 03:00:00  Faisalabad  441.4
10315 2026-01-10 19:00:00      Multan  426.5
10316 2026-01-10 20:00:00      Multan  419.1
10314 2026-01-10 18:00:00      Multan  415.4
1443  2026-01-05 03:00:00  Faisalabad  406.1
1434  2026-01-04 18:00:00  Faisalabad  400.5
1805  2026-01-20 05:00:00  Faisalabad  397.7
1435  2026-01-04 19:00:00  Faisalabad  393.9
1506  2026-01-07 18:00:00  Faisalabad  393.9
10317 2026-01-10 21:00:00      Multan  387.4
10313 2026-01-10 17:00:00      Multan  386.5
1266  2025-12-28 18:00:00  Faisalabad  385.6
1507  2026-01-07 19:00:00  Faisalabad  384.6
1444  2026-01-05 04:00:00  Faisalabad  381.8
844   2025-12-11 04:00:00  Faisalabad  381.8
1554  2026-01-09 18:00:00  Faisalabad  381.8
1267  2025-12-28 19:00:00  Faisalabad  380.0
1746  2026-01-17 18:00:00  Faisalabad  379.0
1436  2026-01-04 20:00:00  Faisalabad  377.2

In [9]:
lahore_df = df[df['city'] == 'Lahore']
lahore_df['pm2_5'].describe()

count    2184.000000
mean      126.761264
std        63.113241
min        16.800000
25%        78.000000
50%       121.100000
75%       166.200000
max       353.900000
Name: pm2_5, dtype: float64

In [10]:
df.groupby('city')['pm2_5'].mean().sort_values(ascending=False)

city
Faisalabad        155.736310
Multan            136.831777
Lahore            126.761264
Sialkot           115.192582
Rahim Yar Khan     72.364927
Islamabad          56.125504
Rawalpindi         56.125504
Peshawar           53.729579
Karachi            37.708974
Quetta             19.104991
Name: pm2_5, dtype: float64

In [11]:
punjab_cities = ['Faisalabad', 'Multan', 'Lahore', 'Sialkot', 'Rahim Yar Khan']
df_punjab = df[df['city'].isin(punjab_cities)]
df_punjab['city'].value_counts()

city
Faisalabad        2184
Lahore            2184
Multan            2184
Rahim Yar Khan    2184
Sialkot           2184
Name: count, dtype: int64